### ISSUE TITLE
Skip P:\ComfyUI_4ALL\ComfyUI\custom_nodes\ComfyUI-InstantID module for custom nodes due to the lack of NODE_CLASS_MAPPINGS.

### ISSUE THREAD

**Issue by ShmuelRonen** [ZHO-ZHO-ZHO/ComfyUI-InstantID#1]
Hi... and thank you!!!
After install the models I got this error:
Skip P:\ComfyUI_4ALL\ComfyUI\custom_nodes\ComfyUI-InstantID module for custom nodes due to the lack of NODE_CLASS_MAPPINGS.
![ERROR](https://github.com/ZHO-ZHO-ZHO/ComfyUI-InstantID/assets/80190186/0b0d9124-df2d-4aee-944b-1dc29393ec3a)

**Comment by johndpope** [comment]
me too. @ZHO-ZHO-ZHO  - can you do a pip freeze  > list.txt ?
```
** ComfyUI startup time: 2024-01-23 10:13:50.096329
** Platform: Linux
** Python version: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
** Python executable: /home/oem/miniconda3/envs/torch2/bin/python
** Log path: /media/2TB/ComfyUI/comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: /media/2TB/ComfyUI/custom_nodes/rgthree-comfy
   0.0 seconds: /media/2TB/ComfyUI/custom_nodes/ComfyUI-Manager

Total VRAM 24257 MB, total RAM 96406 MB
xformers version: 0.0.24.dev719
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using xformers cross attention
FizzleDorf Custom Nodes: Loaded
[comfyui_controlnet_aux] | INFO -> Using ckpts path: /media/2TB/ComfyUI/custom_nodes/comfyui_controlnet_aux/ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
DWPose: Onnxruntime with acceleration providers detected
Total VRAM 24257 MB, total RAM 96406 MB
xformers version: 0.0.24.dev719
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
VAE dtype: torch.bfloat16

Traceback (most recent call last):
  File "/home/oem/miniconda3/envs/torch2/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1382, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/home/oem/miniconda3/envs/torch2/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/oem/miniconda3/envs/torch2/lib/python3.10/site-packages/transformers/models/clip/image_processing_clip.py", line 21, in <module>
    from ...image_processing_utils import BaseImageProcessor, BatchFeature, get_size_dict
  File "/home/oem/miniconda3/envs/torch2/lib/python3.10/site-packages/transformers/image_processing_utils.py", line 28, in <module>
    from .image_transforms import center_crop, normalize, rescale
  File "/home/oem/miniconda3/envs/torch2/lib/python3.10/site-packages/transformers/image_transforms.py", line 47, in <module>
    import tensorflow as tf
  File "/home/oem/miniconda3/envs/torch2/lib/python3.10/site-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/oem/miniconda3/envs/torch2/lib/python3.10/site-packages/tensorflow/python/__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "/home/oem/miniconda3/envs/torch2/lib/python3.10/site-packages/tensorflow/python/eager/context.py", line 29, in <module>
    from tensorflow.core.framework import function_pb2
  File "/home/oem/miniconda3/envs/torch2/lib/python3.10/site-packages/tensorflow/core/framework/function_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "/home/oem/miniconda3/envs/torch2/lib/python3.10/site-packages/tensorflow/core/framework/attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "/home/oem/miniconda3/envs/torch2/lib/python3.10/site-packages/tensorflow/core/framework/tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "/home/oem/miniconda3/envs/torch2/lib/python3.10/site-packages/tensorflow/core/framework/resource_handle_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "/home/oem/miniconda3/envs/torch2/lib/python3.10/site-packages/tensorflow/core/framework/tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/home/oem/miniconda3/envs/torch2/lib/python3.10/site-packages/google/protobuf/descriptor.py", line 553, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/oem/miniconda3/envs/torch2/lib/python3.10/site-packages/diffusers/utils/import_utils.py", line 710, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/home/oem/miniconda3/envs/torch2/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/oem/miniconda3/envs/torch2/lib/python3.10/site-packages/diffusers/pipelines/controlnet/pipeline_controlnet_sd_xl.py", line 23, in <module>
    from transformers import (
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/home/oem/miniconda3/envs/torch2/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1373, in __getattr__
    value = getattr(module, name)
  File "/home/oem/miniconda3/envs/torch2/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1372, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/home/oem/miniconda3/envs/torch2/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1384, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.clip.image_processing_clip because of the following error (look up to see its traceback):
Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/media/2TB/ComfyUI/nodes.py", line 1872, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/media/2TB/ComfyUI/custom_nodes/ComfyUI-InstantID/__init__.py", line 1, in <module>
    from .InstantIDNode import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/media/2TB/ComfyUI/custom_nodes/ComfyUI-InstantID/InstantIDNode.py", line 14, in <module>
    from .pipeline_stable_diffusion_xl_instantid import StableDiffusionXLInstantIDPipeline, draw_kps
  File "/media/2TB/ComfyUI/custom_nodes/ComfyUI-InstantID/pipeline_stable_diffusion_xl_instantid.py", line 38, in <module>
    from diffusers import StableDiffusionXLControlNetPipeline
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/home/oem/miniconda3/envs/torch2/lib/python3.10/site-packages/diffusers/utils/import_utils.py", line 701, in __getattr__
    value = getattr(module, name)
  File "/home/oem/miniconda3/envs/torch2/lib/python3.10/site-packages/diffusers/utils/import_utils.py", line 701, in __getattr__
    value = getattr(module, name)
  File "/home/oem/miniconda3/envs/torch2/lib/python3.10/site-packages/diffusers/utils/import_utils.py", line 700, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/home/oem/miniconda3/envs/torch2/lib/python3.10/site-packages/diffusers/utils/import_utils.py", line 712, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import diffusers.pipelines.controlnet.pipeline_controlnet_sd_xl because of the following error (look up to see its traceback):
Failed to import transformers.models.clip.image_processing_clip because of the following error (look up to see its traceback):
Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

Cannot import /media/2TB/ComfyUI/custom_nodes/ComfyUI-InstantID module for custom nodes: Failed to import diffusers.pipelines.controlnet.pipeline_controlnet_sd_xl because of the following error (look up to see its traceback):
Failed to import transformers.models.clip.image_processing_clip because of the following error (look up to see its traceback):
Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
### Loading: ComfyUI-Inspire-Pack (V0.60)
Error: [Errno 39] Directory not empty: '/media/2TB/ComfyUI/custom_nodes/comfyui-reactor-node/models/facerestore_models' -> '/media/2TB/ComfyUI/models/facerestore_models'
Torch version: 2.1.2+cu121
### Loading: ComfyUI-Manager (V2.2.5)
### ComfyUI Revision: 1923 [ef5a28b5] | Released on '2024-01-20'
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json

```

**Comment by johndpope** [comment]
@ShmuelRonen - make sure you run 
**pip install -r requirements.txt**
