### ISSUE TITLE
Error occurred when executing IDGenerationNode，I've read various tutorials but to no avail.

### ISSUE THREAD

**Issue by Xx-YB** [ZHO-ZHO-ZHO/ComfyUI-InstantID#146]
!!! Exception during processing!!! For single controlnet: `controlnet_conditioning_scale` must be type `float`.
Traceback (most recent call last):
  File "D:\Ai\ConFyUi-Xx\ComfyUI-aki-v1.3\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Ai\ConFyUi-Xx\ComfyUI-aki-v1.3\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Ai\ConFyUi-Xx\ComfyUI-aki-v1.3\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Ai\ConFyUi-Xx\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-InstantID-ZHO\InstantIDNode.py", line 288, in id_generate_image
    output = pipe(
             ^^^^^
  File "D:\Ai\ConFyUi-Xx\ComfyUI-aki-v1.3\.ext\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Ai\ConFyUi-Xx\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-InstantID-ZHO\pipeline_stable_diffusion_xl_instantid.py", line 439, in __call__
    self.check_inputs(
  File "D:\Ai\ConFyUi-Xx\ComfyUI-aki-v1.3\.ext\Lib\site-packages\diffusers\pipelines\controlnet\pipeline_controlnet_sd_xl.py", line 753, in check_inputs
    raise TypeError("For single controlnet: `controlnet_conditioning_scale` must be type `float`.")
TypeError: For single controlnet: `controlnet_conditioning_scale` must be type `float`.

**Comment by Xx-YB** [comment]
Can any great god help me?

**Comment by Xx-YB** [comment]
https://blog.csdn.net/chawk1978/article/details/137665577

The answer in this post is effective. Finally solved it.  Thanks
