### ISSUE TITLE
 StableDiffusionXLControlNetPipeline.__init__() got an unexpected keyword argument 'safety_checker'

### ISSUE THREAD

**Issue by filipemeneses** [ZHO-ZHO-ZHO/ComfyUI-InstantID#16]
Got this error using the workflow: [instant-id.json](https://github.com/ZHO-ZHO-ZHO/ComfyUI-InstantID/files/14029600/instant-id.json)

Used the local workflow sample and changed the path to controlnet models to: 
```
custom_nodes/ComfyUI-InstantID/checkpoints/controlnet
```

UI error:

```
Error occurred when executing IDBaseModelLoader_local:

StableDiffusionXLControlNetPipeline.__init__() got an unexpected keyword argument 'safety_checker'


File "E:\code\stable-difusion\ComfyUI2\execution.py", line 155, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "E:\code\stable-difusion\ComfyUI2\execution.py", line 85, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "E:\code\stable-difusion\ComfyUI2\execution.py", line 78, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "E:\code\stable-difusion\ComfyUI2\custom_nodes\ComfyUI-InstantID\InstantIDNode.py", line 157, in load_model
pipe = StableDiffusionXLInstantIDPipeline.from_single_file(
File "C:\Users\fcmen\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
return fn(*args, **kwargs)
File "C:\Users\fcmen\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\loaders\single_file.py", line 263, in from_single_file
pipe = download_from_original_stable_diffusion_ckpt(
File "C:\Users\fcmen\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\pipelines\stable_diffusion\convert_from_ckpt.py", line 1676, in download_from_original_stable_diffusion_ckpt
pipe = pipeline_class(
```

Terminal error:

```
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "E:\code\stable-difusion\ComfyUI2\execution.py", line 155, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "E:\code\stable-difusion\ComfyUI2\execution.py", line 85, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "E:\code\stable-difusion\ComfyUI2\execution.py", line 78, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "E:\code\stable-difusion\ComfyUI2\custom_nodes\ComfyUI-InstantID\InstantIDNode.py", line 157, in load_model    pipe = StableDiffusionXLInstantIDPipeline.from_single_file(
  File "C:\Users\fcmen\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\fcmen\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\loaders\single_file.py", line 263, in from_single_file
    pipe = download_from_original_stable_diffusion_ckpt(
  File "C:\Users\fcmen\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\pipelines\stable_diffusion\convert_from_ckpt.py", line 1676, in download_from_original_stable_diffusion_ckpt
    pipe = pipeline_class(
TypeError: StableDiffusionXLControlNetPipeline.__init__() got an unexpected keyword argument 'safety_checker'     
```

**Comment by filipemeneses** [comment]
Root cause its that I was using a SD1.5 model, the node only works for SDXL
