### ISSUE TITLE
请问大神，AttributeError: 'StableDiffusionXLInstantIDPipeline' object has no attribute 'dtype' ，这个问题怎么解决？

### ISSUE THREAD

**Issue by zhaowtVincent** [ZHO-ZHO-ZHO/ComfyUI-InstantID#22]
invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}
got prompt
Prompt executor has been patched by Job Iterator!
The config attributes {'controlnet_list': ['controlnet', 'RPMultiControlNetModel'], 'requires_aesthetics_score': False} were passed to StableDiffusionXLInstantIDPipeline, but are not expected and will be ignored. Please verify your model_index.json configuration file.
Keyword arguments {'controlnet_list': ['controlnet', 'RPMultiControlNetModel'], 'requires_aesthetics_score': False, 'local_dir': './checkpoints'} are not expected by StableDiffusionXLInstantIDPipeline and will be ignored.
Loading pipeline components...: 100%|████████████████████████████████████████████████████| 7/7 [00:01<00:00,  4.04it/s]
2024-01-24 15:06:06,114 - root - ERROR - !!! Exception during processing !!!
2024-01-24 15:06:06,116 - root - ERROR - Traceback (most recent call last):
  File "K:\software\ComfyU\ComfyUI_windows_portable\ComfyUI\execution.py", line 155, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\software\ComfyU\ComfyUI_windows_portable\ComfyUI\execution.py", line 85, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\software\ComfyU\ComfyUI_windows_portable\ComfyUI\execution.py", line 78, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\software\ComfyU\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantID\InstantIDNode.py", line 190, in load_ip_adapter_instantid
    pipe.load_ip_adapter_instantid(face_adapter)
  File "K:\software\ComfyU\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantID\pipeline_stable_diffusion_xl_instantid.py", line 156, in load_ip_adapter_instantid
    self.set_image_proj_model(model_ckpt, image_emb_dim, num_tokens)
  File "K:\software\ComfyU\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantID\pipeline_stable_diffusion_xl_instantid.py", line 174, in set_image_proj_model
    self.image_proj_model = image_proj_model.to(self.device, dtype=self.dtype)
                                                                   ^^^^^^^^^^
  File "K:\software\ComfyU\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\configuration_utils.py", line 137, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'StableDiffusionXLInstantIDPipeline' object has no attribute 'dtype'

Prompt executed in 12.06 seconds
got prompt
Prompt executor has been patched by Job Iterator!
2024-01-24 15:06:37,405 - root - ERROR - !!! Exception during processing !!!
2024-01-24 15:06:37,406 - root - ERROR - Traceback (most recent call last):
  File "K:\software\ComfyU\ComfyUI_windows_portable\ComfyUI\execution.py", line 155, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\software\ComfyU\ComfyUI_windows_portable\ComfyUI\execution.py", line 85, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\software\ComfyU\ComfyUI_windows_portable\ComfyUI\execution.py", line 78, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "K:\software\ComfyU\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantID\InstantIDNode.py", line 190, in load_ip_adapter_instantid
    pipe.load_ip_adapter_instantid(face_adapter)
  File "K:\software\ComfyU\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantID\pipeline_stable_diffusion_xl_instantid.py", line 156, in load_ip_adapter_instantid
    self.set_image_proj_model(model_ckpt, image_emb_dim, num_tokens)
  File "K:\software\ComfyU\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantID\pipeline_stable_diffusion_xl_instantid.py", line 174, in set_image_proj_model
    self.image_proj_model = image_proj_model.to(self.device, dtype=self.dtype)
                                                                   ^^^^^^^^^^
  File "K:\software\ComfyU\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\configuration_utils.py", line 137, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'StableDiffusionXLInstantIDPipeline' object has no attribute 'dtype'

Prompt executed in 0.71 seconds

**Comment by HaydenReeve** [comment]
No solution yet, see #5

**Comment by camoody1** [comment]
Same issue for me. Frustrating.

**Comment by rodrgomes** [comment]
I fixed updating diffusers.. I was with 0.21 with the same error. After installed 0.24 it got fixed

**Comment by camoody1** [comment]
> I fixed updating diffusers.. I was with 0.21 with the same error. After installed 0.24 it got fixed

Please don't hate me for asking this, but how would I go about finding which version I'm on and then updating to the newest version? Thank you

**Comment by rodrgomes** [comment]
> > I fixed updating diffusers.. I was with 0.21 with the same error. After installed 0.24 it got fixed
> 
> Please don't hate me for asking this, but how would I go about finding which version I'm on and then updating to the newest version? Thank you

In my case, with windows portable, I use 

python_embeded\python.exe -m pip show diffusers

**Comment by camoody1** [comment]
@rodrgomes Thank you. I appreciate you taking the time to drop your answer here. I hope it works for me, as well.

**Comment by EightiesPower** [comment]
> @rodrgomes Thank you. I appreciate you taking the time to drop your answer here. I hope it works for me, as well.

Did it? I've done the update and still the same error...

**Comment by rodrgomes** [comment]
> > @rodrgomes Thank you. I appreciate you taking the time to drop your answer here. I hope it works for me, as well.
> 
> Did it? I've done the update and still the same error...

Are you sure that you updated the package in right (virtual) environment? That was the only thing that I did to pass that error

**Comment by jeantimex** [comment]
I had the same problem on my Mac M1, then I just ran `pip install -U -r requirements.txt` in `ComfyUI/custom_nodes/ComfyUI-InstantID` and restart ComfyUI, the problem is solved, I have no idea what is going on.

However, it seems it's going to take forever to generate an image for me, sigh...

**Comment by camoody1** [comment]
@rodrgomes I updated my diffusers to 0.25.0 (the latest, I believe). And I was able to get past my error!

Unnnnfortunately, I ran out of VRAM just before the final image was rendered. The "InstantID Generation" node gets to 100% in the console... there's a slight pause... and then out of vram error. 😭 I have an RTX 3060 12GB card, so I was really hoping I would be able to run this. Alas, I guess not.

**Comment by riccardobiagi** [comment]
> I had the same problem on my Mac M1, then I just ran `pip install -U -r requirements.txt` in `ComfyUI/custom_nodes/ComfyUI-InstantID` and restart ComfyUI, the problem is solved, I have no idea what is going on.
> 
> However, it seems it's going to take forever to generate an image for me, sigh...

Hi! Same problem here, I tried your solution but I get this error in the terminal:
ERROR: Could not find a version that satisfies the requirement onnxruntime-gpu (from versions: none)
ERROR: No matching distribution found for onnxruntime-gpu

I'm not a code guy.. can I ask you if you know what is talking about and how to fix it? 
Thank you
