### ISSUE TITLE
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Read timed out. (read timeout=None)

### ISSUE THREAD

**Issue by wangwenqiao666** [ZHO-ZHO-ZHO/ComfyUI-InstantID#25]
Traceback (most recent call last):
  File "F:\AIProject\ComfyUI_CMD\ComfyUI\execution.py", line 155, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AIProject\ComfyUI_CMD\ComfyUI\execution.py", line 85, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AIProject\ComfyUI_CMD\ComfyUI\execution.py", line 78, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AIProject\ComfyUI_CMD\ComfyUI\custom_nodes\ComfyUI-InstantID\nodes.py", line 76, in sample
    StableDiffusionXLPipeline.from_single_file(
  File "F:\AIProject\ComfyUI_CMD\ComfyUI\.ext\Lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "F:\AIProject\ComfyUI_CMD\ComfyUI\.ext\Lib\site-packages\diffusers\loaders\single_file.py", line 263, in from_single_file
    pipe = download_from_original_stable_diffusion_ckpt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AIProject\ComfyUI_CMD\ComfyUI\.ext\Lib\site-packages\diffusers\pipelines\stable_diffusion\convert_from_ckpt.py", line 1319, in download_from_original_stable_diffusion_ckpt
    original_config_file = BytesIO(requests.get(config_url).content)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AIProject\ComfyUI_CMD\ComfyUI\.ext\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AIProject\ComfyUI_CMD\ComfyUI\.ext\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AIProject\ComfyUI_CMD\ComfyUI\.ext\Lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AIProject\ComfyUI_CMD\ComfyUI\.ext\Lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AIProject\ComfyUI_CMD\ComfyUI\.ext\Lib\site-packages\requests\adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Read timed out. (read timeout=None)
![image](https://github.com/ZHO-ZHO-ZHO/ComfyUI-InstantID/assets/55267900/e472eb87-2763-4e12-b389-3809fe615c9a)

What happened?

**Comment by wangwenqiao666** [comment]
![image](https://github.com/ZHO-ZHO-ZHO/ComfyUI-InstantID/assets/55267900/a185c8eb-08ac-4594-b35e-80974b55a145)

**Comment by guahunyo** [comment]
我也一样

**Comment by junxinjay** [comment]
俺也一样

**Comment by wangwenqiao666** [comment]
look my solved：https://blog.csdn.net/weixin_41529012/article/details/135955693?spm=1001.2014.3001.5501
