### ISSUE TITLE
Return type mismatch between linked nodes: insightface, INSIGHTFACE != INSIGHTFACEMODEL

### ISSUE THREAD

**Issue by HaydenReeve** [ZHO-ZHO-ZHO/ComfyUI-InstantID#27]
No errors or warnings during boot, all requirements satisfied and present.

Workflow doesn't even attempt to load.

```
ERROR:root:Failed to validate prompt for output 12:
ERROR:root:* IDGenerationNode 15:
ERROR:root:  - Return type mismatch between linked nodes: insightface, INSIGHTFACE != INSIGHTFACEMODEL
ERROR:root:Output will be ignored
invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}
```

**Comment by HaydenReeve** [comment]
Not going to pretend I know what I'm doing, but in making the following changes I managed to progress to the next error at least.

```diff
diff --git a/InstantIDNode.py b/InstantIDNode.py
index 88d0684..4ec1876 100644
--- a/InstantIDNode.py
+++ b/InstantIDNode.py
@@ -62,7 +62,7 @@ class InsightFaceLoader_Node_Zho:
             },
         }

-    RETURN_TYPES = ("INSIGHTFACEMODEL",)
+    RETURN_TYPES = ("INSIGHTFACE",)
     FUNCTION = "load_insight_face_antelopev2"
     CATEGORY = "📷InstantID"

@@ -228,7 +228,7 @@ class IDGenerationNode_Zho:
             "required": {
                 "face_image": ("IMAGE",),
                 "pipe": ("MODEL",),
-                "insightface": ("INSIGHTFACEMODEL",),
+                "insightface": ("INSIGHTFACE",),
:
diff --git a/InstantIDNode.py b/InstantIDNode.py
index 88d0684..4ec1876 100644
--- a/InstantIDNode.py
+++ b/InstantIDNode.py
@@ -62,7 +62,7 @@ class InsightFaceLoader_Node_Zho:
             },
         }

-    RETURN_TYPES = ("INSIGHTFACEMODEL",)
+    RETURN_TYPES = ("INSIGHTFACE",)
     FUNCTION = "load_insight_face_antelopev2"
     CATEGORY = "📷InstantID"

@@ -228,7 +228,7 @@ class IDGenerationNode_Zho:
             "required": {
                 "face_image": ("IMAGE",),
                 "pipe": ("MODEL",),
-                "insightface": ("INSIGHTFACEMODEL",),
+                "insightface": ("INSIGHTFACE",),
```

**Comment by HaydenReeve** [comment]
Also recommend adding

```diff
@@ -186,6 +186,9 @@ class Ipadapter_instantidLoader_Node_Zho:
     def load_ip_adapter_instantid(self, pipe, Ipadapter_instantid_path, filename):
         # 使用hf_hub_download方法获取PhotoMaker文件的路径
         face_adapter = os.path.join(Ipadapter_instantid_path, filename)
+        
+        if not os.path.exists(face_adapter):
+            raise FileNotFoundError(f"Cannot find '{face_adapter}' as it does not exist.")

         # load adapter
         pipe.load_ip_adapter_instantid(face_adapter)
```

As I realised the paths here are quite confusing

**Comment by Starzilla29** [comment]
Is this the result of having IPAdapter installed? because the insightface loader node conflicts with the InstantID insightface loader node? perhaps giving it a different naming scheme?

**Comment by cerarslan** [comment]
Same

**Comment by CaptainGrock** [comment]
Same as well, thanks for resolving (won't work otherwise)

**Comment by camoody1** [comment]
Getting these same errors. Hopefully, someone will get a working InstantID soon.

**Comment by HaydenReeve** [comment]
> Is this the result of having IPAdapter installed? because the insightface loader node conflicts with the InstantID insightface loader node? perhaps giving it a different naming scheme?
> 
> EDIT: I uninstalled IPAdapter to see if that was the case, I had to rename .json after that, had to redownload all the antelopev2 files, now trying to solve why it says CUDA isn't loaded, but it works on my cpu I am pretty sure it is the IPAdapter conflict for this particular error unfortunately... hopefully we get an update that fixes this conflict

That would check out.

If anybody wants to avoid uninstalling the default IPAdapter you can make the changes here instead:

https://github.com/ZHO-ZHO-ZHO/ComfyUI-InstantID/issues/27#issuecomment-1907979128

I'll get around to making a pull request at some point...

**Comment by camoody1** [comment]
@HaydenReeve In which file should I make these changes?

**Comment by camoody1** [comment]
I made the second change you suggested regarding the face_adapter path error. I didn't make the first set of Insightface changes because I don't see those lines in the InstantIDNode.py file.

I am now getting this error message:

got prompt
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 155, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 85, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 78, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantID\InstantIDNode.py", line 194, in load_ip_adapter_instantid
    pipe.load_ip_adapter_instantid(face_adapter)
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantID\pipeline_stable_diffusion_xl_instantid.py", line 156, in load_ip_adapter_instantid
    self.set_image_proj_model(model_ckpt, image_emb_dim, num_tokens)
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantID\pipeline_stable_diffusion_xl_instantid.py", line 174, in set_image_proj_model
    self.image_proj_model = image_proj_model.to(self.device, dtype=self.dtype)
                                                                   ^^^^^^^^^^
  File "H:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\configuration_utils.py", line 137, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'StableDiffusionXLInstantIDPipeline' object has no attribute 'dtype'

Prompt executed in 36.00 seconds

**Comment by HaydenReeve** [comment]
You're now looking at the issue described in #5

**Comment by camoody1** [comment]
@HaydenReeve Here's another InstantID GitHub project that looks like it was forked from here. It doesn't even have the file that you had me modify. Sadly, I get the same error message with it, too. 🤷🏼‍♂️

https://github.com/huxiuhan/ComfyUI-InstantID

**Comment by HaydenReeve** [comment]
You don't need a linux installation.

Just clone the main comfy repo, install the python prereqs on your system, and then run using an editor such as Jetbrains Fleet or VSCode which can execute the launch command.

The repo you linked was actually the first one I tried. Didn't work for me either.

**Comment by pauloalves86** [comment]
> @HaydenReeve I made the second change you suggested regarding the face_adapter path error. I didn't make the first set of Insightface changes because I don't see those lines in the InstantIDNode.py file.
> 
> I am now getting this error message:
> 
> got prompt ERROR:root:!!! Exception during processing !!! ERROR:root:Traceback (most recent call last): File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 155, in recursive_execute output_data, output_ui = get_output_data(obj, input_data_all) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 85, in get_output_data return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 78, in map_node_over_list results.append(getattr(obj, func)(**slice_dict(input_data_all, i))) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantID\InstantIDNode.py", line 194, in load_ip_adapter_instantid pipe.load_ip_adapter_instantid(face_adapter) File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantID\pipeline_stable_diffusion_xl_instantid.py", line 156, in load_ip_adapter_instantid self.set_image_proj_model(model_ckpt, image_emb_dim, num_tokens) File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantID\pipeline_stable_diffusion_xl_instantid.py", line 174, in set_image_proj_model self.image_proj_model = image_proj_model.to(self.device, dtype=self.dtype) ^^^^^^^^^^ File "H:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\configuration_utils.py", line 137, in **getattr** raise AttributeError(f"'{type(self).**name**}' object has no attribute '{name}'") AttributeError: 'StableDiffusionXLInstantIDPipeline' object has no attribute 'dtype'
> 
> Prompt executed in 36.00 seconds

Just `pip install -U -r requeriments.txt` from inside custom_nodes/ComfyUI-InstantID.

**Comment by yueziii** [comment]
hi, are you using v1 workflow? try use v2 workflow.

**Comment by waltm** [comment]
> `InstantIDNode.py` and yes.
> 
> The red is what it looked like before the change, the green is what it looks like after the change.

Hi, when I make those changes and reload ComfyUI, it is showing all the InstantID nodes in red as if they are missing.  If I then install missing nodes, it reverts the changes.  Am I supposed to change something else other than changing "INSIGHTFACEMODEL" to "INSIGHTFACE"?
