### ISSUE TITLE
 No module named 'diffusers', but its installed?

### ISSUE THREAD

**Issue by Xardous** [ZHO-ZHO-ZHO/ComfyUI-InstantID#28]
I'm getting the error upon startup:
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1872, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantID\__init__.py", line 1, in <module>
    from .InstantIDNode import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantID\InstantIDNode.py", line 1, in <module>
    import diffusers
ModuleNotFoundError: No module named 'diffusers'

Cannot import D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantID module for custom nodes: No module named 'diffusers'

Usually to fix this i would install diffusers via pip but I already have it installed (requirement already satisfied).

**Comment by Hansynily** [comment]
Try pip inside python_embedded/ not from system wide pip

**Comment by alexbofa** [comment]
`Manager` → `Install PIP packages` → put this link `diffusers==0.25.1` and `restart`.

**Comment by Xardous** [comment]
Fixed after reinstalling comfy and using python_embedded to reinstall necessary modules as recommended by @Hansynily
