### ISSUE TITLE
comfyUI manager: 

### ISSUE THREAD

**Issue by manassm** [ZHO-ZHO-ZHO/ComfyUI-InstantID#30]
![image](https://github.com/ZHO-ZHO-ZHO/ComfyUI-InstantID/assets/70854401/483fa7c6-1eb3-4e92-85ad-351b98496c38)
Im on windows, trying to install it via comfy manager and followed the instruction to download files and place in appropraite folder, but keep getting "import failed" error

my CMD log on bootup:

C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --preview-method auto
** ComfyUI startup time: 2024-01-24 12:02:39.111625
** Platform: Windows
** Python version: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
** Python executable: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\python_embeded\python.exe
** Log path: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Marigold
   0.0 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 16376 MB, total RAM 32540 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4080 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
[Allor]: 0 nodes were overridden.
[Allor]: 12 modules were enabled.
[Allor]: 98 nodes were loaded.
### Loading: ComfyUI-Impact-Pack (Subpack: V0.4)
[Impact Pack] Wildcards loading done.
Traceback (most recent call last):
  File "C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1872, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantID\__init__.py", line 1, in <module>
    from .InstantIDNode import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantID\InstantIDNode.py", line 14, in <module>
    from insightface.app import FaceAnalysis
ModuleNotFoundError: No module named 'insightface'

Cannot import C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantID module for custom nodes: No module named 'insightface'
### ComfyUI Revision: 1928 [3762e676] | Released on '2024-01-23'
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
------------------------------------------------
Comfyroll Custom Nodes v1.55 :  165 Nodes Loaded
------------------------------------------------
[comfyui_controlnet_aux] | INFO -> Using ckpts path: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
DWPose: Onnxruntime with acceleration providers detected
FizzleDorf Custom Nodes: Loaded
Requirement already satisfied: segment_anything in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from -r requirements.txt (line 1)) (1.0)
Requirement already satisfied: timm in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from -r requirements.txt (line 2)) (0.9.12)
Requirement already satisfied: addict in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from -r requirements.txt (line 3)) (2.4.0)
Requirement already satisfied: yapf in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from -r requirements.txt (line 4)) (0.40.2)
Requirement already satisfied: torch>=1.7 in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from timm->-r requirements.txt (line 2)) (2.1.2+cu121)
Requirement already satisfied: torchvision in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from timm->-r requirements.txt (line 2)) (0.16.2+cu121)
Requirement already satisfied: pyyaml in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from timm->-r requirements.txt (line 2)) (6.0.1)
Requirement already satisfied: huggingface-hub in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from timm->-r requirements.txt (line 2)) (0.19.4)
Requirement already satisfied: safetensors in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from timm->-r requirements.txt (line 2)) (0.4.1)
Requirement already satisfied: importlib-metadata>=6.6.0 in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from yapf->-r requirements.txt (line 4)) (7.0.1)
Requirement already satisfied: platformdirs>=3.5.1 in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from yapf->-r requirements.txt (line 4)) (4.1.0)
Requirement already satisfied: tomli>=2.0.1 in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from yapf->-r requirements.txt (line 4)) (2.0.1)
Requirement already satisfied: zipp>=0.5 in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from importlib-metadata>=6.6.0->yapf->-r requirements.txt (line 4)) (3.17.0)
Requirement already satisfied: filelock in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.7->timm->-r requirements.txt (line 2)) (3.13.1)
Requirement already satisfied: typing-extensions in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.7->timm->-r requirements.txt (line 2)) (4.9.0)
Requirement already satisfied: sympy in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.7->timm->-r requirements.txt (line 2)) (1.12)
Requirement already satisfied: networkx in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.7->timm->-r requirements.txt (line 2)) (3.2.1)
Requirement already satisfied: jinja2 in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.7->timm->-r requirements.txt (line 2)) (3.1.2)
Requirement already satisfied: fsspec in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from torch>=1.7->timm->-r requirements.txt (line 2)) (2023.12.2)
Requirement already satisfied: requests in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from huggingface-hub->timm->-r requirements.txt (line 2)) (2.31.0)
Requirement already satisfied: tqdm>=4.42.1 in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from huggingface-hub->timm->-r requirements.txt (line 2)) (4.66.1)
Requirement already satisfied: packaging>=20.9 in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from huggingface-hub->timm->-r requirements.txt (line 2)) (23.2)
Requirement already satisfied: numpy in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from torchvision->timm->-r requirements.txt (line 2)) (1.26.2)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from torchvision->timm->-r requirements.txt (line 2)) (9.5.0)
Requirement already satisfied: colorama in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from tqdm>=4.42.1->huggingface-hub->timm->-r requirements.txt (line 2)) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from jinja2->torch>=1.7->timm->-r requirements.txt (line 2)) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->huggingface-hub->timm->-r requirements.txt (line 2)) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->huggingface-hub->timm->-r requirements.txt (line 2)) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->huggingface-hub->timm->-r requirements.txt (line 2)) (1.26.18)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->huggingface-hub->timm->-r requirements.txt (line 2)) (2023.11.17)
Requirement already satisfied: mpmath>=0.19 in c:\users\ssm05\desktop\myfolder\art\comfyui_windows_portable\python_embeded\lib\site-packages (from sympy->torch>=1.7->timm->-r requirements.txt (line 2)) (1.3.0)
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 198 nodes successfully.

        "Art is not a thing; it is a way." - Elbert Hubbard

Import times for custom nodes:
   0.0 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\clip_text_encode_split.py
   0.0 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\canvas_tab
   0.0 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-portrait-master-zh-cn
   0.0 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Image-Selector
   0.0 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-use-everywhere
   0.0 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Logic
   0.0 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\masquerade-nodes-comfyui
   0.0 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\stability-ComfyUI-nodes
   0.0 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-post-processing-nodes
   0.0 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-yanc
   0.0 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
   0.0 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Text_Image-Composite
   0.0 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\images-grid-comfy-plugin
   0.0 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PhotoMaker
   0.0 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
   0.0 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Marigold
   0.0 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.0 seconds (IMPORT FAILED): C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantID
   0.1 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Moore-AnimateAnyone
   0.1 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\LCM_Inpaint-Outpaint_Comfy
   0.1 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.1 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.1 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes
   0.2 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Gemini
   0.2 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.3 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.3 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\clipseg.py
   0.4 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Allor
   0.9 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui
   1.7 seconds: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_segment_anything

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: C:\Users\ssm05\Desktop\myFolder\Art\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json

**Comment by hany-cmd** [comment]
I have the same issue

**Comment by alexbofa** [comment]
`Manager` → `Install PIP packages` → put this link `https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp311-cp311-win_amd64.whl` and `restart`. If you have Python 3.11.

For Python 3.10 `https://github.com/Gourieff/sd-webui-reactor/raw/main/example/insightface-0.7.3-cp310-cp310-win_amd64.whl`

**Comment by hany-cmd** [comment]
@alexbofa  that works for me thx

**Comment by merecesarchviz** [comment]
I have the same error! and doing what you recomend:

Manager → Install PIP packages → put this link https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp311-cp311-win_amd64.whl and restart. If you have Python 3.11.

For Python 3.10 https://github.com/Gourieff/sd-webui-reactor/raw/main/example/insightface-0.7.3-cp310-cp310-win_amd64.whl

dont solve it! any other alternative?

**Comment by alexbofa** [comment]
> I have the same error! and doing what you recomend:
> 
> Manager → Install PIP packages → put this link https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp311-cp311-win_amd64.whl and restart. If you have Python 3.11.
> 
> For Python 3.10 https://github.com/Gourieff/sd-webui-reactor/raw/main/example/insightface-0.7.3-cp310-cp310-win_amd64.whl
> 
> I got this errors:
> 
> ### Loading: ComfyUI-Inspire-Pack (V0.60.1)
> [Impact Pack] Wildcards loading done. Traceback (most recent call last): File "F:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1810, in load_custom_node module_spec.loader.exec_module(module) File "", line 940, in exec_module File "", line 241, in _call_with_frames_removed File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantID__init__.py", line 1, in from .InstantIDNode import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantID\InstantIDNode.py", line 14, in from insightface.app import FaceAnalysis ModuleNotFoundError: No module named 'insightface'
> 
> Cannot import F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantID module for custom nodes: No module named 'insightface'
> 
> ### Loading: ComfyUI-Manager (V2.2.5)
> dont solve it! any other alternative?

You may have a problem with Python paths. Because of this, the module may not be mapped and installed. 
I advise you to:
1. Re-download **python_embedded** → [ComfyUI_windows_portable_nvidia_cu121_or_cpu.7z](https://github.com/comfyanonymous/ComfyUI/releases/download/latest/ComfyUI_windows_portable_nvidia_cu121_or_cpu.7z)
2. **Manager** → **Install PIP packages** → put this link `https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp311-cp311-win_amd64.whl` → ok
and `opencv-python==4.8.1.78` → ok
and `segment-anything` → ok
and `omegaconf` → ok
and `restart`
3. **Manager** → **Install Custom Nodes** → **Filter: import failed** → Check all ✅ the broken notes everywhere and click `Fix It`

Then all the nodes should work for you. In addition to complex software requirements (PhotoMaker, InstantID, Lora-Training-in-Comfy & etc.)
I hope that in the coming updates the developers will simplify the installation of these nodes.

**Comment by zhoobin021** [comment]
> `Manager` → `Install PIP packages` → put this link `https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp311-cp311-win_amd64.whl` and `restart`. If you have Python 3.11.
> 
> For Python 3.10 `https://github.com/Gourieff/sd-webui-reactor/raw/main/example/insightface-0.7.3-cp310-cp310-win_amd64.whl`

thank you, your solution worked for me.

some how I installed python 3.10.11 but when I launch ComfyUI it says python version 3.11.6.
I tried with https://github.com/Gourieff/sd-webui-reactor/raw/main/example/insightface-0.7.3-cp310-cp310-win_amd64.whl
but it didn't work, but with https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp311-cp311-win_amd64.whl it worked.

**Comment by haohaocreates** [comment]
> `Manager` → `Install PIP packages` → put this link `https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp311-cp311-win_amd64.whl` and `restart`. If you have Python 3.11.
> 
> For Python 3.10 `https://github.com/Gourieff/sd-webui-reactor/raw/main/example/insightface-0.7.3-cp310-cp310-win_amd64.whl`

worked for me too!

**Comment by Priestru** [comment]
> `Manager` → `Install PIP packages` → put this link `https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp311-cp311-win_amd64.whl` and `restart`. If you have Python 3.11.
> 
> For Python 3.10 `https://github.com/Gourieff/sd-webui-reactor/raw/main/example/insightface-0.7.3-cp310-cp310-win_amd64.whl`

Be blessed with the best wife and be healthy for life.

**Comment by naiwenmoerthegod** [comment]
> Be blessed with the best wife and be healthy for life.

Be blessed with the best wife and be healthy for life.

**Comment by nerminba** [comment]
> https://github.com/Gourieff/sd-webui-reactor/raw/main/example/insightface-0.7.3-cp310-cp310-win_amd64.whl

does not exist anymore
