### ISSUE TITLE
Some notes on getting this to work

### ISSUE THREAD

**Issue by lanzer** [ZHO-ZHO-ZHO/ComfyUI-InstantID#32]
Here are a few notes that the install guide didn't mention, as well as some issues I found along the way:

1) If you're new to this, be sure to have ComfyUI Manager installed (https://github.com/ltdrdata/ComfyUI-Manager)
2) Once you load any sample workflow, if there are nodes missing, just go into the ComfyUI Manager and select "Install Missing Custom Nodes".  Lots of videos out there talks about using ComfyUI Manager that's worth watching if you're new.
3) Avoid the workflows that doesn't mention "locally" in the filename.  The "fromhub" workflows attempt to download the SDXL model directly from Huggingface, but chances are you already have your model downloaded.  And you need to have credentials configured to get this to work.  It's just unnecessary.
4) The "V1.0 InstantID_locally【Zho】.json" workflow uses the "InstantID Generation" node that has a bug from which keep it from working with the insightface loader node.  Just avoid this workflow until the bug is fixed (as of 01/24/2024)
5) Which leaves only "V2.0 InstantID_locally_pose_ref【Zho】.json" as the workflow that currently works without modifications. :)
6) Install notes ask you to download config.json from (https://huggingface.co/InstantX/InstantID/tree/main/ControlNetModel), but note that the filename downloaded will be named ControlNetModel_config.json.  You'll need to rename the file back to "config.json" in order for it to work.  The files should be placed under (ustom_nodes/ConfyUI-InstantID/checkpoints)
7) If you want to get the art gallery workflow working, simply replace the "ID Base Model Loader from Hub" node to "ID Base Model Loader locally" node.  Double click on an empty area on your workflow to start search.  Type in "idbasemodelloader" and you'll see the two versions available.  Select and local one and replace with the hub version.  (you can't search by the actual node title as the metadata was not properly named)

That's all the gotchas I found.  Good luck and have fun!

**Comment by camoody1** [comment]
I keep getting this same error message regardless of which local workflow I try:

got prompt
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 155, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 85, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 78, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantID\InstantIDNode.py", line 194, in load_ip_adapter_instantid
    pipe.load_ip_adapter_instantid(face_adapter)
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantID\pipeline_stable_diffusion_xl_instantid.py", line 156, in load_ip_adapter_instantid
    self.set_image_proj_model(model_ckpt, image_emb_dim, num_tokens)
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantID\pipeline_stable_diffusion_xl_instantid.py", line 174, in set_image_proj_model
    self.image_proj_model = image_proj_model.to(self.device, dtype=self.dtype)
                                                                   ^^^^^^^^^^
  File "H:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\configuration_utils.py", line 137, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'StableDiffusionXLInstantIDPipeline' object has no attribute 'dtype'
