### ISSUE TITLE
Invalid URL 'None': No scheme supplied.

### ISSUE THREAD

**Issue by skibol75** [ZHO-ZHO-ZHO/ComfyUI-InstantID#42]
Hey everyone i'm doing my best to make it work but i'm stuck on something i keep getting this error when it comes to the "ID Base Model Loader Locally". I use the base model sdxl, did all the requirements needed but nothing.. help me please, thanks you

<img width="852" alt="Capture d’écran 2024-01-25 à 12 01 39" src="https://github.com/ZHO-ZHO-ZHO/ComfyUI-InstantID/assets/128597517/ba5d32af-0858-4f14-a41b-513139475a45">

**Here is the error from the terminal :** 

ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/Users/amibouzi/ComfyUI/execution.py", line 155, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amibouzi/ComfyUI/execution.py", line 85, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amibouzi/ComfyUI/execution.py", line 78, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amibouzi/ComfyUI/custom_nodes/ComfyUI-InstantID/InstantIDNode.py", line 158, in load_model
    pipe = StableDiffusionXLInstantIDPipeline.from_single_file(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amibouzi/miniconda3/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/amibouzi/miniconda3/lib/python3.11/site-packages/diffusers/loaders/single_file.py", line 263, in from_single_file
    pipe = download_from_original_stable_diffusion_ckpt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amibouzi/miniconda3/lib/python3.11/site-packages/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py", line 1319, in download_from_original_stable_diffusion_ckpt
    original_config_file = BytesIO(requests.get(original_config_file, verify=False).content)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amibouzi/miniconda3/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amibouzi/miniconda3/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amibouzi/miniconda3/lib/python3.11/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amibouzi/miniconda3/lib/python3.11/site-packages/requests/sessions.py", line 486, in prepare_request
    p.prepare(
  File "/Users/amibouzi/miniconda3/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/Users/amibouzi/miniconda3/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?

Prompt executed in 0.12 seconds

**Comment by skibol75** [comment]
hello thank you for your help ! i still get the same error wether it's sdxl base or anything else. i made it work on my windows computer but here i'm on mac m2 and cannot manage to make it work
thank you

**Comment by johndpope** [comment]
attempt to get this working first as sanity check - there's a requirements.txt file - might help https://github.com/InstantID/InstantID/tree/main/gradio_demo
