### ISSUE TITLE
Made a video on how to get it running Here

### ISSUE THREAD

**Issue by if-ai** [ZHO-ZHO-ZHO/ComfyUI-InstantID#57]
https://www.youtube.com/watch?v=BGlbN3PR4RU

I don't want to span. If this is not helpful please close it or add it to a discussion session.
I show how to install it and fix InsightFace

**Comment by lunatico67** [comment]
> https://www.youtube.com/watch?v=BGlbN3PR4RU
> 
> I don't want to span. If this is not helpful please close it or add it to a discussion session. I show how to install it and fix InsightFace

Hi!  I get this error:
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "C:\Users\surco\Documents\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\surco\Documents\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\surco\Documents\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\surco\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantID\InstantIDNode.py", line 158, in load_model
    pipe = StableDiffusionXLInstantIDPipeline.from_single_file(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\surco\Documents\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\surco\Documents\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\loaders\single_file.py", line 263, in from_single_file
    pipe = download_from_original_stable_diffusion_ckpt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\surco\Documents\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\pipelines\stable_diffusion\convert_from_ckpt.py", line 1249, in download_from_original_stable_diffusion_ckpt
    raise ValueError(BACKENDS_MAPPING["omegaconf"][1])
ValueError:
{0} requires the omegaconf library but it was not found in your environment. You can install it with pip: `pip
install omegaconf`
