### ISSUE TITLE
Error after InstantID Generation node

### ISSUE THREAD

**Issue by razvanab** [ZHO-ZHO-ZHO/ComfyUI-InstantID#6]
I get this error after the InstantID Generation node:

` ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "H:\Stable-diffusion\ComfyUI\execution.py", line 155, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "H:\Stable-diffusion\ComfyUI\execution.py", line 85, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "H:\Stable-diffusion\ComfyUI\custom_nodes\ComfyUI-0246\utils.py", line 363, in new_func
    res_value = old_func(*final_args, **kwargs)
  File "H:\Stable-diffusion\ComfyUI\execution.py", line 78, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "H:\Stable-diffusion\ComfyUI\nodes.py", line 1415, in save_images
    full_output_folder, filename, counter, subfolder, filename_prefix = folder_paths.get_save_image_path(filename_prefix, self.output_dir, images[0].shape[1], images[0].shape[0])
AttributeError: 'str' object has no attribute 'shape' `

**Comment by VJDemien** [comment]
Same

**Comment by pointave** [comment]
It's probably the face you are transferring is too small. Add padding or find another photo

**Comment by johndpope** [comment]
check the boot up logs when you start comfy. you maybe missing modules.
https://github.com/ZHO-ZHO-ZHO/ComfyUI-InstantID/pull/17/files

**Comment by ludogemma** [comment]
me too same error but after some tries i got it to work .. but ... only with some images.. and i couldn't figure yet what is .. i mean some 512x512 works.. some don't .. i thought the file size no! the file type neither... some .webp works .. but also some png...
most of image that works are less than 512px... anyway is almost impossibile right now to predict and understand the images that could works..
