### ISSUE TITLE
Exception during processing

### ISSUE THREAD

**Issue by lunatico67** [ZHO-ZHO-ZHO/ComfyUI-InstantID#61]
!!! Exception during processing !!!
Traceback (most recent call last):
  File "C:\Users\Luna\Documents\ComfyUI_windows_portable\python_embeded\lib\site-packages\diffusers\configuration_utils.py", line 428, in load_config
    config_dict = cls._dict_from_json_file(config_file)
  File "C:\Users\Luna\Documents\ComfyUI_windows_portable\python_embeded\lib\site-packages\diffusers\configuration_utils.py", line 551, in _dict_from_json_file
    return json.loads(text)
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Luna\Documents\ComfyUI_windows_portable\ComfyUI\execution.py", line 155, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\Users\Luna\Documents\ComfyUI_windows_portable\ComfyUI\execution.py", line 85, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\Users\Luna\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-0246\utils.py", line 373, in new_func
    res_value = old_func(*final_args, **kwargs)
  File "C:\Users\Luna\Documents\ComfyUI_windows_portable\ComfyUI\execution.py", line 78, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\Users\Luna\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantID\InstantIDNode.py", line 96, in load_idcontrolnet
    controlnet = ControlNetModel.from_pretrained(controlnet_path, torch_dtype=torch.float16)
  File "C:\Users\Luna\Documents\ComfyUI_windows_portable\python_embeded\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\Luna\Documents\ComfyUI_windows_portable\python_embeded\lib\site-packages\diffusers\models\modeling_utils.py", line 712, in from_pretrained
    config, unused_kwargs, commit_hash = cls.load_config(
  File "C:\Users\Luna\Documents\ComfyUI_windows_portable\python_embeded\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\Luna\Documents\ComfyUI_windows_portable\python_embeded\lib\site-packages\diffusers\configuration_utils.py", line 432, in load_config
    raise EnvironmentError(f"It looks like the config file at '{config_file}' is not a valid JSON file.")
OSError: It looks like the config file at 'C:\Users\Luna\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantID\checkpoints\controlnet\config.json' is not a valid JSON file.

**Comment by koko93s** [comment]
@lunatico67 did you ever solve this?  In regards to the missing config.json?

**Comment by koko93s** [comment]
Nevermind figured it out.  I just didnt download the config file from the controlnet repo

**Comment by lunatico67** [comment]
> Nevermind figured it out. I just didnt download the config file from the controlnet repo

Hi Koko
When trying to install InstantID my comfyui broke down. From what I've read on the internet it happens to most people who try it. It would be a great help if you created a video tutorial on how to install it, there are many of us who are not computer scientists.
