### ISSUE TITLE
import failed

### ISSUE THREAD

**Issue by INKXXXXYY** [ZHO-ZHO-ZHO/ComfyUI-InstantID#65]
** ComfyUI startup time: 2024-01-27 11:23:28.885930
** Platform: Linux
** Python version: 3.8.18 (default, Sep 11 2023, 13:40:15) 
[GCC 11.2.0]
** Python executable: /root/miniconda3/envs/hqy/bin/python
** Log path: /root/autodl-tmp/hqy_comfy/ComfyUI/comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: /root/autodl-tmp/hqy_comfy/ComfyUI/custom_nodes/ComfyUI-Manager

Total VRAM 24248 MB, total RAM 257838 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA RTX A5000 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
### ComfyUI Revision: 1931 [89507f8a] | Released on '2024-01-25'
Traceback (most recent call last):
  File "/root/autodl-tmp/hqy_comfy/ComfyUI/nodes.py", line 1872, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/autodl-tmp/hqy_comfy/ComfyUI/custom_nodes/ComfyUI-InstantID/__init__.py", line 1, in <module>
    from .InstantIDNode import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/root/autodl-tmp/hqy_comfy/ComfyUI/custom_nodes/ComfyUI-InstantID/InstantIDNode.py", line 24, in <module>
    def apply_style(style_name: str, positive: str, negative: str = "") -> tuple[str, str]:
TypeError: 'type' object is not subscriptable

Cannot import /root/autodl-tmp/hqy_comfy/ComfyUI/custom_nodes/ComfyUI-InstantID module for custom nodes: 'type' object is not subscriptable

**Comment by INKXXXXYY** [comment]
gpt：
根据您提供的错误信息，问题似乎出现在 `/root/autodl-tmp/hqy_comfy/ComfyUI/custom_nodes/ComfyUI-InstantID/InstantIDNode.py` 文件中。具体来说，错误是一个 `TypeError`，指出 `'type' object is not subscriptable`。这个错误通常是由于尝试使用 Python 3.8 或更早版本的类型注解语法时出现的。

在 Python 3.8 中，类型注解对于集合类型（如 `list`, `dict`, `tuple`）需要使用 `typing` 模块中的类，而不是像 Python 3.9+ 那样直接使用内置类型。例如，要声明一个元素类型为 `str` 的 `tuple`，在 Python 3.9+ 中可以直接写作 `tuple[str, str]`，但在 Python 3.8 中，你需要从 `typing` 模块导入 `Tuple` 并使用 `Tuple[str, str]`。

错误发生在这行代码：
```python
def apply_style(style_name: str, positive: str, negative: str = "") -> tuple[str, str]:
```

为了修复这个问题，你需要修改此行以使用 Python 3.8 兼容的类型注解。以下是修复后的代码：

1. 首先，确保在文件顶部导入 `Tuple`：
   ```python
   from typing import Tuple
   ```

2. 然后，修改 `apply_style` 函数的返回类型注解：
   ```python
   def apply_style(style_name: str, positive: str, negative: str = "") -> Tuple[str, str]:
   ```

应用这些更改后，代码应该与 Python 3.8 兼容。这应该解决导入问题。
