### ISSUE TITLE
HF_HOME

### ISSUE THREAD

**Issue by fogostudio** [ZHO-ZHO-ZHO/ComfyUI-InstantID#88]
I'm getting this error at launch:

Traceback (most recent call last):
  File "F:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantID\__init__.py", line 1, in <module>
    from .InstantIDNode import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantID\InstantIDNode.py", line 1, in <module>
    import diffusers
  File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\__init__.py", line 5, in <module>
    from .utils import (
  File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\utils\__init__.py", line 21, in <module>
    from .constants import (
  File "F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\utils\constants.py", line 17, in <module>
    from huggingface_hub.constants import HF_HOME
ImportError: cannot import name 'HF_HOME' from 'huggingface_hub.constants' (F:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\constants.py)

**Comment by fee0103** [comment]
just uninstall huggingface_hub and install it again; Or  upgrade it .
That is because the version is too low.
