### ISSUE TITLE
Insightface problem

### ISSUE THREAD

**Issue by Torcelllo** [ZHO-ZHO-ZHO/ComfyUI-InstantID#94]
#######################################################################
[ComfyUI-Manager] Starting dependency installation/(de)activation for the extension

Install: pip packages for 'B:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantID'
 Collecting insightface
   Using cached insightface-0.7.3.tar.gz (439 kB)
   Installing build dependencies: started
   Installing build dependencies: finished with status 'done'
   Getting requirements to build wheel: started
   Getting requirements to build wheel: finished with status 'error'
[!]   error: subprocess-exited-with-error
[!]
[!]   Getting requirements to build wheel did not run successfully.
[!]   exit code: 1
[!]
[!]   [18 lines of output]
[!]   Traceback (most recent call last):
[!]     File "B:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
[!]       main()
[!]     File "B:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
[!]       json_out['return_val'] = hook(**hook_input['kwargs'])
[!]                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]     File "B:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
[!]       return hook(config_settings)
[!]              ^^^^^^^^^^^^^^^^^^^^^
[!]     File "B:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
[!]       return self._get_build_requires(config_settings, requirements=['wheel'])
[!]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]     File "B:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
[!]       self.run_setup()
[!]     File "B:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
[!]       exec(code, locals())
[!]     File "<string>", line 11, in <module>
[!]   ModuleNotFoundError: No module named 'Cython'
[!]   [end of output]
[!]
[!]   note: This error originates from a subprocess, and is likely not a problem with pip.
[!] error: subprocess-exited-with-error
[!]
[!] Getting requirements to build wheel did not run successfully.
[!] exit code: 1
[!]
[!] See above for output.
[!]
[!] note: This error originates from a subprocess, and is likely not a problem with pip.

[ComfyUI-Manager] Startup script completed.
#######################################################################

**Comment by ViniciusFXavier** [comment]
Same here

**Comment by Torcelllo** [comment]
ChatGPT gave me this ... but it's still something beyond my grasp!

![ChatGPT Assert Detection fault](https://github.com/ZHO-ZHO-ZHO/ComfyUI-InstantID/assets/114806454/265ff660-59a3-4ff1-9fb9-60bf53982be0)
